jaffle_shop_demo:
  outputs:
    dev:
      type: databricks
      catalog: workspace
      schema: alwyn_dev
      host: "{{ env_var('DBT_HOST') }}"
      http_path: "{{ env_var('DBT_HTTP_PATH') }}"
      auth_type: oauth
      threads: 4
  target: dev
